 jenkins_cli_jar: /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar
 jenkins_install_dir: /var/lib/jenkins

 jenkins_user: jenkins
 jenkins_authorized_keys:
   - "{{playbook_dir}}/files/ssh_keys/svoronenko.pub"

 my_java_version: 8

 my_jenkins_domain: "littlebigmake.local"
 my_jenkins_host: "cd"

 my_jenkins_plugins:
   - build-pipeline-plugin
   - copyartifact # https://wiki.jenkins-ci.org/display/JENKINS/Copy+Artifact+Plugin
   - credentials # https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin
   - delivery-pipeline-plugin # https://wiki.jenkins-ci.org/display/JENKINS/Delivery+Pipeline+Plugin
   - environment-script # https://wiki.jenkins-ci.org/display/JENKINS/Environment+Script+Plugin
   - git
   - ghprb # https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin
#    - greenballs # https://wiki.jenkins-ci.org/display/JENKINS/Green+Balls
#   - hipchat # https://wiki.jenkins-ci.org/display/JENKINS/HipChat+Plugin
   - junit # https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Plugin
   - matrix-auth # https://wiki.jenkins-ci.org/display/JENKINS/Matrix+Authorization+Strategy+Plugin
   - matrix-project #https://wiki.jenkins-ci.org/display/JENKINS/Matrix+Project+Plugin
   - modernstatus # http://updates.jenkins-ci.org/latest/modernstatus.hpi
   - parameterized-trigger #https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Trigger+Plugin
   - rebuild # https://wiki.jenkins-ci.org/display/JENKINS/Rebuild+Plugin
   - ssh
   - s3 # https://wiki.jenkins-ci.org/display/JENKINS/S3+Plugin
   - throttle-concurrents #https://wiki.jenkins-ci.org/display/JENKINS/Throttle+Concurrent+Builds+Plugin
   - blueocean # https://wiki.jenkins-ci.org/display/JENKINS/Blue+Ocean+Plugin


 my_ufw_rules_allow:
    - {
        port: 22,
        proto: tcp
       }
    - {
        port: 80,
        proto: tcp
       }
    - {
        port: 443,
        proto: tcp
       }


 my_ufw_rules_allow_from_hosts: []
#     - {
#         port: 22,
#         proto: tcp,
#         address: "10.10.0.0/16"
#       }
